language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: npm run dist
script: npm test
before_deploy: echo 'All unit tests passed; Successfully built distribution assets;
  Preparing to deploy NYPL Blogs to AWS'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: nypl-blogs
  env: nypl-blogs-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: nypl-blogs-production
  on:
    repo: NYPL/dgx-blogs
    branch: master
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: nypl-blogs
  env: nypl-blogs-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: nypl-blogs-qa
  on:
    repo: NYPL/dgx-blogs
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: nypl-blogs
  env: nypl-blogs-development
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: nypl-blogs-development
  on:
    repo: NYPL/dgx-blogs
    branch: development
    # We've removed development EB, so skip deployment:
    condition: 1 == 0
after_deploy: echo 'Successfully executed deploy trigger for NYPL Blogs on AWS'
env:
  global:
    secure: oCNguOL7IrGpru/OgzHB2CWkcklmjcrktHA+pZwdNpEpAshvQUfwEaU1qDGolLVsnBW5M3XylCxCKNorY0o++E4vO3CcrduTM+Hl0peDiXRGNXy2XtY2qJQq+jseMiYMTm7syP9Jlj8tfhLHK+3pwJ0fKb6Gsmwj8ACn5pjXVgWqWezHxyCGrhyPldPrL8nturG+vJOF85B/s9W+TubPiX8O4x5uL15wzbnh7BGlv/Dfk0CHK2iwQubCiAyezOX9NNRdOj45ED2aEqk+D4MoY88aFS1NHg8JEvFu240oiT5Q2M4ifvu5m7Vzq+qtJAW7HqolqFj4wsNz+tv71YKCN4ThvQeWJIzS5ohREL0l7LzJps63w/Th/jtNF7ByPDTG4+TcxSmC9DyATeloGbTRF9N8RvNbmzmr9Yj5zKYQXM/eKWlFldPzjYhzOwuAtkeCAkSFhCwQ4fHQ4Wgicka1A1eGHC91x6ROcsnATcHa3kmP0Gr6PxUb81WGOUHvlK3LI/1yNEyDeuyJtPEe6yeqBLVfVnU4bNpgunIbSB6FE6aRVLLy5yUNOq+qGtNDVtO88mdoV1d8zPz9gBXTn32l8h3MEWnAgBcRG3yL3DydgRcy1xn2CFkRtCeBdNmdn9q5pkfkMVg3ro7hM1lPkF3svKGWqifv/iNEUgmKVQE9TtY=
